### ISSUE TITLE
您的代码支持CPU训练吗？

### ISSUE THREAD

**Issue by shenhongcai** [Liumihan/CRNN_pytorch#2]
您好，大佬。我在本地MacOS,CPU环境 下跑了你的项目，数据集也是按照您的数据集格式改的。应该没有问题。但是发现您的这份代码是在GPU下训练的，我想问问代码支持CPU训练吗。如果方便能否添加您的联系方式，方便咨询一下。1152874847@qq.com 万分感激！

**Comment by Liumihan** [comment]
https://github.com/Liumihan/CRNN_pytorch/blob/62e1162ab33230179bde793bdda8a9d3c9c8b2f8/crnn/config.py#L19
你可以将这个改成 device='cpu' 就可以了， 不过会很慢哦
