### ISSUE TITLE
你没有对图片进行等比例缩放

### ISSUE THREAD

**Issue by shenhongcai** [Liumihan/CRNN_pytorch#3]
你好，我跑了你的代码。按照CRNN 论文中的描述，应该对图片固定height，然后width=(height/img_height)*image_width, 其中  image_height,  image_width为训练图片的高度和长度。我在你的代码里看到的是，你是强行将图片resize到（32，280）。这样的话，有可能会导致图片变形。

**Comment by Liumihan** [comment]
谢谢，确实应该是等比例的缩放才对，我在后面的代码里面改成等比例的缩放了。后面弃坑了，就没有更新代码了。

**Comment by Liumihan** [comment]
谢谢，确实应该是等比例的缩放才对，我在后面的代码里面改成等比例的缩放了。后面弃坑了，就没有更新代码了。
